### PR TITLE
Ptoken filter

### PR DESCRIPTION
**Pull request by vporton**
Issue https://github.com/raid-guild/gitcoinco-web/issues/13

##### Description

Implemented filtering `/users` by presence of a personal token.

Design needs an improvement, probably.

##### Testing

Not tested, because there are apparently no users with a personal token yet.

### CODE REVIEW

**Comment by vporton** [comment]
Tested.

**Comment by vporton** [comment]
Should we also filter by `token_state='completed'`?

**Comment by proofoftom** [comment]
Can this be rebased on the latest staging? Since there's some merges in here this PR includes a bunch of unnecessary commits and file changes

**Comment by vporton** [comment]
> Can this be rebased on the latest staging? Since there's some merges in here this PR includes a bunch of unnecessary commits and file changes

Done. After this deleted and re-created some migrations. You may need to reset your DB (i.e. `make fresh`) to make it work after this :-(

**Pull request merged**
